#!/usr/bin/python

import debian.debian_support
import urllib
import subprocess
import os
import sys
import time
import tempfile
import shutil


# output usage
if len(sys.argv) != 3 and len(sys.argv) != 4 :
  print("Usage: ./findReverseDependencies <package_name> <distribution_codename> [<architecture>]")
  print("Example: ./findReverseDependencies libmtca4u-deviceaccess-dev xenial")
  sys.exit()

# parse command line arguments
package = sys.argv[1]
codename = sys.argv[2]
if len(sys.argv) == 4 :
  arch = sys.argv[3]
else:
  arch = "amd64"

# download Packages file from the DESY DOOCS apt repositories
subprocess.call(["wget", "-q", "http://doocspkgs.desy.de/pub/doocs/dists/"+codename+"/main/binary-"+arch+"/Packages", "-O", "Packages.DESY"])

# open Packages file and parse it
PackageFile = debian.debian_support.PackageFile("Packages.DESY")

# search for packages depending on the specified package
print("List of packages depending on '"+package+"' on "+codename+"/"+arch+":")
for Package in PackageFile:
  PackageAsDictionary = dict(Package)
  if 'Depends' in PackageAsDictionary:
    depends = PackageAsDictionary['Depends']
    depends_array = depends.split(", ")
    for dependency in depends_array:
      dependency_split = dependency.split(" ")
      if(dependency_split[0] == package):
        print(PackageAsDictionary['Package'])

