#!/bin/bash -e

# Shell script to log into the pbuilder chroot environment (needed for debugging purposes only)
# create directory holding pbuilder images
WD=`realpath $(dirname "$0")`
mkdir -p "${WD}/pbuilder-base"

function showHelp() {
  # print usage
  echo "Usage:"
  echo "  ./loginToPbuilder [-p|--preseed] <distributionCodeName>"
  echo "     - Log in to the image for the given distribution."
  exit 1
}

# Parse command line arguments
PRESEED_REPOS=""
while true; do
    case $1 in
        -h|--help)
            showHelp
            exit 0
            ;;
        -p|--preseed)
            PRESEED_REPOS="`pwd`/preseed"
            ;;
        *)
            DISTRIBUTION="$1"
            break;;
    esac
    shift
done

if [ -z "$DISTRIBUTION" ]; then
  showHelp
  exit 1
fi

source config.sh
HOOKDIR="`pwd`/pbuilder-hooks"

echo "Using repository ${DEBIANREPOSITORY}"

PBUILDER_IMAGE="${WD}/pbuilder-base/base-${DISTRIBUTION}.tgz"
if [ ! -f ${PBUILDER_IMAGE} ]; then
  echo "The selected distribution was not yet initialised."
  exit 1
fi

${WD}/updateLocalRepos

export PRESEED_REPOS

sudo -E pbuilder --login --distribution ${DISTRIBUTION} --override-config --components "main universe"                 \
                 --mirror "${MIRROR}"                                                                                  \
                 --othermirror "${MIRRORLIST}"                                                                         \
                 --basetgz "${PBUILDER_IMAGE}" --bindmounts "${LOCAL_REPOS} ${PRESEED_REPOS}"                          \
                 --hookdir "${HOOKDIR}"
