#!/bin/bash -e

# Shell script to create or update the pbuilder image used in makeDebianPackage

# create directory holding pbuilder images
WD=`realpath $(dirname "$0")`
mkdir -p "${WD}/pbuilder-base"

# Parse command line arguments
if [ -z "$1" ] ; then
  # print usage
  echo "Usage:"
  echo "  ./updatePBuilder <distributionCodeName>"
  echo "     - Update the image for the given distribution. If no image exists, create it first."
  echo ""
  echo "  ./updatePBuilder --setup <distributionCodeName>"
  echo "     - Create a fresh image for the given distribution, even if it exists already."
  exit 1
elif [ "$1" == "--setup" ] ; then
  if [ -z "$2" ] ; then
    echo "Missing parameter to --setup"
    exit 1
  fi
  DISTRIBUTION=$2
  rm -rf "pbuilder-base/base-${DISTRIBUTION}.tgz"
else
  DISTRIBUTION=$1
fi

PBUILDER_IMAGE="${WD}/pbuilder-base/base-${DISTRIBUTION}.tgz"
if [ ! -f ${PBUILDER_IMAGE} ]; then
  sudo pbuilder --create --distribution $DISTRIBUTION --basetgz "${PBUILDER_IMAGE}" || exit 1
fi

${WD}/updateLocalRepos
LOCAL_REPOS=${WD}/pbuilder-result

MIRRORLIST="deb [trusted=yes] file://${LOCAL_REPOS} ${DISTRIBUTION} main|deb [trusted=yes] http://doocspkgs.desy.de/pub/doocs ${DISTRIBUTION} main"
sudo pbuilder --update --distribution ${DISTRIBUTION} --override-config --components "main universe"                  \
              --othermirror "${MIRRORLIST}"  \
              --basetgz "${PBUILDER_IMAGE}" --bindmounts "${LOCAL_REPOS}"         || exit 1

