#!/bin/bash
echo "==================> Running $0"
echo ">>>>>>>>> $PRESEED_REPOS"
if [ -n "$PRESEED_REPOS" ] ; then
    echo ">>>>>>>>> $PRESEED_REPOS <<<< success!!"
    cat /etc/apt/sources.list
    echo "deb [trusted=yes] file://$PRESEED_REPOS ${DISTRIBUTION} main " >> /etc/apt/sources.list
    apt-get update
fi
